# C++ では set とか使わず変数名にする

agent_features = [
    ("NEIGHBOR_PATTERN", 2**12),
    ("LENGTH", 77),
    ("DIFFERENCE_LENGTH_1ST", 21),
    ("DIFFERENCE_LENGTH_2ND", 21),
    ("DIFFERENCE_LENGTH_3RD", 21),
    ("DIFFERENCE_LENGTH_4TH", 21),
    ("RELATIVE_POSITION_TAIL", 77),
    ("RELATIVE_POSITION_OPPONENT_HEAD", 77),
    ("MOVE_HISTORY", 4**4),
    ("RELATIVE_POSITION_TAIL_ON_PLANE_X", 61),
    ("RELATIVE_POSITION_TAIL_ON_PLANE_Y", 61),
    ("N_REACHABLE_POSITIONS_WITHIN_1_STEP", 5),
    ("N_REACHABLE_POSITIONS_WITHIN_2_STEPS", 13),
    ("N_REACHABLE_POSITIONS_WITHIN_3_STEPS", 25),
    ("N_REACHABLE_POSITIONS_WITHIN_4_STEPS", 40),
    ("N_REACHABLE_POSITIONS_WITHIN_5_STEPS", 57),
    ("N_OPPONENTS_SHARING_REACHABLE_POSITIONS_WITHIN_1_STEP", 4),
    ("N_OPPONENTS_SHARING_REACHABLE_POSITIONS_WITHIN_2_STEPS", 4),
    ("N_OPPONENTS_SHARING_REACHABLE_POSITIONS_WITHIN_3_STEPS", 4),
    ("N_OPPONENTS_SHARING_REACHABLE_POSITIONS_WITHIN_4_STEPS", 4),
    ("N_OPPONENTS_SHARING_REACHABLE_POSITIONS_WITHIN_5_STEPS", 4),
    ("N_EXCLUSIVELY_REACHABLE_POSITIONS_WITHIN_1_STEP", 5),
    ("N_EXCLUSIVELY_REACHABLE_POSITIONS_WITHIN_2_STEPS", 13),
    ("N_EXCLUSIVELY_REACHABLE_POSITIONS_WITHIN_3_STEPS", 25),
    ("N_EXCLUSIVELY_REACHABLE_POSITIONS_WITHIN_4_STEPS", 40),
    ("N_EXCLUSIVELY_REACHABLE_POSITIONS_WITHIN_5_STEPS", 57),
    ("RELATIVE_POSITION_OPPONENT_HEAD_FROM_TAIL", 77),
    ("RELATIVE_POSITION_FOOD", 77),
]  # type: list[tuple[str,int]]

dict_agent_feature_to_index = {}
index = 0
for name, num in agent_features:
    dict_agent_feature_to_index[name] = index
    index += num


